### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by scientist1642** [evansolomon/lipaste#1]
Maybe it's a good idea to make  `lipaste chrome` command which would be alias for `CHROMEPATH $(lipaste)`.

**Comment by evansolomon** [comment]
Not sure if `CHROMEPATH` is a variable/function that is supposed to exist, but it doesn't seem to be in my shell. That said, `open` is probably close enough to what it would do. You could do `lipaste | xargs open` or the slightly shorter `open $(lipaste)`.

**Comment by scientist1642** [comment]
Yeah you are right, I was just thinking making it easier for non coders. (so that he/she doesnt have to copy an url). but probably there are few such people who see this app. (your last sentence would do the job in readme in this case)
good work!

**Comment by scientist1642** [comment]
oh i forgot it would be it appears in your lichess account you dont have to copy. ok never mind :D

**Comment by evansolomon** [comment]
You can also `lipaste | pbcopy` on osx.
